'use strict';
const LOCAL_MODE=true;
const STORAGE_KEY='trening-bartka-v1:'+location.pathname.replace(/[^/]*$/,'');
async function readWorkouts(){const raw=localStorage.getItem(STORAGE_KEY);if(raw===null)return [];const data=JSON.parse(raw);if(!validBackup(data))throw Error('Uszkodzona historia');return data}
async function writeWorkout(snapshot){const all=await readWorkouts();const i=all.findIndex(w=>w.id===snapshot.id);if(i<0)all.push(snapshot);else all[i]=snapshot;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(all))}catch{throw Error('Brak miejsca lub zapis w przeglądarce jest zablokowany. Pobierz kopię danych.')}}
const names={bench:'Wyciskanie na ławce płaskiej',ohp:'Wyciskanie barków OHP',fly:'Rozpiętki',pushdown:'Triceps — wyciąg w dół',raise:'Wznosy bokiem',overhead:'Triceps — nad głową',lat:'Lat pulldown',wide:'Wiosłowanie — szeroki chwyt',single:'Single arm high-cable row',preacher:'Modlitewnik',curl:'Biceps na ławeczce',reverse:'Rozpiętki tyłem',smith:'Skos na Smithie',narrow:'Wiosłowanie — wąski chwyt'};
const plans=[{name:'PUSH',day:'Poniedziałek',area:'Klatka · barki · triceps',ex:[['bench',3],['ohp',3],['fly',3],['pushdown',2],['raise',3],['overhead',2]]},{name:'PULL',day:'Środa',area:'Plecy · biceps · tył barków',ex:[['lat',3],['wide',3],['single',3],['preacher',2],['curl',2],['reverse',3]]},{name:'PUSH-PULL',day:'Piątek',area:'Klatka · plecy · ramiona',ex:[['bench',3],['smith',3],['lat',3],['narrow',3],['preacher',3],['pushdown',3],['raise',3]]}];
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseDate=s=>new Date(s+'T12:00:00');
const fmt=(s,opts={day:'numeric',month:'short'})=>parseDate(s).toLocaleDateString('pl-PL',opts);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const recommended=()=>({1:0,3:1,5:2}[new Date().getDay()]??(new Date().getDay()<3?0:new Date().getDay()<5?1:2));
let chosen=recommended(),view='home',workouts=[],active=null,selectedDate=localDate(),month=new Date(new Date().getFullYear(),new Date().getMonth(),1),progressId='bench',saveTimer,saveQueue=Promise.resolve(),revision=0,loadError=false;
const app=document.querySelector('#app');
const completed=()=>workouts.filter(w=>w.status==='complete').sort((a,b)=>b.date.localeCompare(a.date)||b.started.localeCompare(a.started));
const doneSets=w=>w.exercises.flatMap(e=>e.sets.filter(s=>s.done));
const volume=w=>doneSets(w).reduce((n,s)=>n+Number(s.kg)*Number(s.reps),0);
const num=n=>Number(n).toLocaleString('pl-PL',{maximumFractionDigits:1});
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),4000)}
async function load(){try{workouts=await readWorkouts();active=workouts.find(w=>w.status==='draft')||null;loadError=false;render()}catch{loadError=true;app.innerHTML='<h1>Twoje treningi</h1><p class="alert">Nie udało się wczytać historii.</p><button data-action="retry">Spróbuj ponownie</button>'}}
function persist(){if(!active)return Promise.resolve();const snapshot=JSON.parse(JSON.stringify(active));const rev=++revision;status('Zapisywanie…');saveQueue=saveQueue.catch(()=>{}).then(async()=>{await writeWorkout(snapshot);const i=workouts.findIndex(w=>w.id===snapshot.id);if(i<0)workouts.push(snapshot);else workouts[i]=snapshot;if(rev===revision)status('Zapisano');return snapshot});saveQueue.catch(e=>{status('Błąd zapisu — kliknij „Zapisz ponownie”');toast(e.message)});return saveQueue}
function status(s){const e=document.querySelector('#save-status');if(e)e.textContent=s}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist(),450)}
function start(){if(active){view='training';render();return}const p=plans[chosen];active={id:crypto.randomUUID(),date:localDate(),started:new Date().toISOString(),status:'draft',plan:chosen,exercises:p.ex.map(([id,n])=>({id,sets:Array.from({length:n},()=>({kg:'',reps:'',done:false}))}))};view='training';render();persist()}
function previous(id){for(const w of completed()){const e=w.exercises.find(x=>x.id===id);if(e&&e.sets.some(s=>s.done))return e.sets.filter(s=>s.done).map(s=>`${num(s.kg)} kg × ${s.reps}`).join(' · ')}return 'Pierwszy zapis — ustal swój punkt wyjścia'}
function historyItem(w){return `<button class="history-item" data-history="${esc(w.id)}"><span><strong>${plans[w.plan].name}</strong><span class="muted small">${fmt(w.date)} · ${doneSets(w).length} serii</span></span><span class="record">${num(volume(w))} kg<small class="muted" style="display:block">objętość</small></span></button>`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===(view==='training'?'home':view)));if(loadError)return; if(view==='home')home();if(view==='training')training();if(view==='calendar')calendar();if(view==='progress')progress()}
function performance(w){
 const prior=completed().filter(x=>x.id!==w.id&&x.plan===w.plan&&(x.date<w.date||x.date===w.date&&x.started<w.started)).sort((a,b)=>b.date.localeCompare(a.date)||b.started.localeCompare(a.started))[0];
 if(!prior)return null;
 const before=volume(prior);if(before<=0)return null;
 const after=volume(w),delta=(after-before)/before*100,score=Math.max(0,Math.min(100,Math.round(50+delta*2.5)));
 return {score,delta,before,after,prior,sets:doneSets(w).length-doneSets(prior).length,label:delta>=20?'Świetny progres':delta>2?'Wynik w górę':delta>=-2?'Podobny wynik':delta>-20?'Mniejsza objętość':'Duży spadek wyniku'};
}
function scoreCard(w){const r=performance(w);if(!r)return '<section class="score-card"><h3>Punkt odniesienia</h3><p class="small muted">Pierwszy trening tego planu. Ocena pojawi się przy następnym porównywalnym treningu.</p></section>';return `<section class="score-card"><div class="row"><div><div class="eyebrow">Wynik względem poprzedniego treningu</div><h3>${r.label}</h3></div><strong class="score-number">${r.score}<small>%</small></strong></div><div class="score-track" role="meter" aria-label="Ocena objętości treningowej" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${r.score}"><span style="width:${r.score}%"></span></div><p class="small">${r.delta>=0?'+':''}${num(r.delta)}% objętości · ${r.sets>=0?'+':''}${r.sets} serii</p><details><summary>Jak liczymy wynik?</summary><p class="small muted">Porównanie z ${fmt(r.prior.date)} dla tego samego planu. Suma ciężar × powtórzenia we wszystkich wykonanych seriach: ${num(r.before)} → ${num(r.after)} kg. Pominięte serie nie dodają objętości.</p><p class="small muted">50% = bez zmiany; 100% = wzrost o co najmniej 20%; 0% = spadek o co najmniej 20%. Ocena = 50 + 2,5 × procent zmiany, w zakresie 0–100. To wskaźnik objętości, nie ocena techniki ani przyrostu mięśni. Porównuj ten sam sprzęt i sposób liczenia ciężaru.</p></details></section>`}
function home(){const p=plans[chosen];app.innerHTML=`<section class="welcome"><div class="eyebrow">${new Date().toLocaleDateString('pl-PL',{weekday:'long',day:'numeric',month:'long'})}</div><h1>Witaj, Bartek<span>.</span></h1><p class="welcome-intro">Dobry moment na trening.</p><div class="plan-picker" aria-label="Wybierz plan treningowy">${plans.map((p,i)=>`<button data-plan="${i}" aria-pressed="${i===chosen}" class="plan-choice ${i===chosen?'selected':''}"><span class="plan-title">${p.name}</span><span class="plan-day">${p.day}</span>${i===chosen?'<span class="selection-dot" aria-hidden="true">✓</span>':''}</button>`).join('')}</div><div class="plan-description">${p.area}<span>${p.ex.length} ćwiczeń</span></div><button class="primary wide start-button" data-action="start">${active?'Wznów '+plans[active.plan].name:'Trenuj'}</button>${active?'<p class="small muted">Twój rozpoczęty trening czeka. Możesz go dokończyć.</p>':`<p class="small muted home-note">${chosen===recommended()?'Plan zaproponowany na dziś.':'Twój wybór na dziś.'} Możesz wybrać inny.</p>`}${completed().filter(w=>w.date===localDate()).slice(0,1).map(scoreCard).join('')}<details class="plan-details"><summary>Zobacz ćwiczenia</summary>${p.ex.map(([id,n],i)=>`<div class="exercise-preview"><span class="number">${String(i+1).padStart(2,'0')}</span><strong>${names[id]}</strong><span>${n} serie</span></div>`).join('')}</details>${backupControls()}</section>`}
const photoIds=new Set(['bench','ohp','fly','pushdown','raise','overhead','lat','preacher','curl','reverse','smith','narrow']);
const photoVariants={fly:'Wariant na zdjęciu: rozpiętki z hantlami.',reverse:'Wariant na zdjęciu: rozpiętki tyłem z hantlami.',preacher:'Wariant na zdjęciu: modlitewnik ze sztangą.',overhead:'Wariant na zdjęciu: wyciąg z liną nad głową.'};
let wizardBusy=false;
function cursor(){if(!active)return [0,0];if(Array.isArray(active.cursor)&&Number.isInteger(active.cursor[0])&&active.cursor[0]>=0&&active.cursor[0]<=active.exercises.length){const [i,j]=active.cursor;if(i===active.exercises.length||Number.isInteger(j)&&j>=0&&j<active.exercises[i].sets.length)return [i,j]}for(let i=0;i<active.exercises.length;i++){const j=active.exercises[i].sets.findIndex(s=>!s.done);if(j>=0)return [i,j]}return [active.exercises.length,0]}
function training(){if(!active){view='home';home();return}const w=active,[i,j]=cursor(),e=w.exercises[i];if(!e){app.innerHTML=`<section class="wizard summary-screen"><div class="eyebrow">${plans[w.plan].name}</div><h1>Trening wykonany.</h1><p class="muted">Zapisz go w kalendarzu i sprawdź swój progres.</p>${scoreCard(w)}<div class="summary-numbers"><div><strong>${doneSets(w).length}</strong><span>wykonanych serii</span></div><div><strong>${num(volume(w))} <small>kg</small></strong><span>łączna objętość</span></div></div><label class="small muted">Data treningu<input class="date-input" type="date" id="workout-date" max="${localDate()}" value="${w.date}"></label><button class="primary wide" data-action="finish">Zakończ i zapisz trening</button><button class="text-button wide" data-wizard="back">Wróć do ostatniej serii</button><div id="save-status" class="save-status">Wyniki są zapisane jako rozpoczęty trening</div></section>`;return}
const set=e.sets[j];app.innerHTML=`<section class="wizard"><div class="row wizard-top"><button class="text-button" data-view="home">Zamknij</button><span class="small muted">${plans[w.plan].name} · Ćwiczenie ${i+1} z ${w.exercises.length}</span></div><div class="wizard-progress" aria-label="Ćwiczenie ${i+1} z ${w.exercises.length}">${w.exercises.map((_,k)=>`<span class="${k<=i?'filled':''}"></span>`).join('')}</div><h1 class="exercise-title">${names[e.id]}</h1>${photoIds.has(e.id)?`<figure class="exercise-demo"><div class="photo-pair"><div><img src="./exercises/${e.id}-0.jpg" alt="${names[e.id]} — pozycja początkowa"><span>Początek</span></div><div><img src="./exercises/${e.id}-1.jpg" alt="${names[e.id]} — pozycja końcowa"><span>Koniec ruchu</span></div></div><figcaption>${photoVariants[e.id]||'Dwie fazy ruchu.'} <a href="https://github.com/yuhonas/free-exercise-db" target="_blank" rel="noopener noreferrer">Źródło zdjęć</a></figcaption></figure>`:''}<div class="series-heading"><span class="series-label">Seria <strong>${j+1}</strong> z ${e.sets.length}</span><button class="text-button" data-wizard="add">+ Dodaj serię</button></div><form id="series-form"><div class="result-fields"><label>Ciężar <span>kg</span><input id="series-kg" aria-label="Ciężar w kilogramach" type="number" inputmode="decimal" min="0" max="2000" step="any" placeholder="0" required value="${esc(set.kg)}" data-current="kg"></label><label>Powtórzenia<input id="series-reps" aria-label="Liczba powtórzeń" type="number" inputmode="numeric" min="1" max="1000" step="1" placeholder="0" required value="${esc(set.reps)}" data-current="reps"></label></div><p class="previous-result">Ostatnio: ${previous(e.id)}</p><button type="submit" class="primary wide next-button">${j+1<e.sets.length?'Zapisz serię i dalej':i+1<w.exercises.length?'Zapisz i następne ćwiczenie':'Zapisz ostatnią serię'}</button></form>${j+1<e.sets.length?'<button class="last-series wide" data-wizard="last">To była ostatnia seria</button>':''}<div class="row wizard-bottom"><button class="text-button" data-wizard="back" ${i===0&&j===0?'disabled':''}>Poprzednia seria</button><button class="text-button" data-action="save">Zapisz ponownie</button></div><div id="save-status" class="save-status">Postęp zapisuje się automatycznie</div></section>`}
function currentSet(){const [i,j]=cursor();return active?.exercises[i]?.sets[j]}
async function nextSeries(last=false){if(wizardBusy)return;const form=document.querySelector('#series-form');if(!form||!form.reportValidity())return;const [i,j]=cursor(),e=active.exercises[i],set=e.sets[j];set.kg=document.querySelector('#series-kg').value;set.reps=document.querySelector('#series-reps').value;set.done=true;const oldSets=e.sets.slice();if(last)e.sets=e.sets.slice(0,j+1);active.cursor=j+1<e.sets.length?[i,j+1]:[i+1,0];clearTimeout(saveTimer);wizardBusy=true;app.querySelectorAll('button,input').forEach(b=>b.disabled=true);try{await persist();training();window.scrollTo(0,0)}catch{e.sets=oldSets;active.cursor=[i,j];training();status('Nie zapisano — spróbuj ponownie. Wpisane wyniki pozostały.')}finally{wizardBusy=false}}
function detail(w){return `<div class="detail">${scoreCard(w)}<div class="row"><h2>${plans[w.plan].name}</h2><span class="muted">${doneSets(w).length} serii</span></div>${w.exercises.filter(e=>e.sets.some(s=>s.done)).map(e=>`<section><h3>${names[e.id]}</h3><p>${e.sets.filter(s=>s.done).map((s,i)=>`${i+1}. ${num(s.kg)} kg × ${s.reps}`).join('<br>')}</p></section>`).join('')}<p class="muted small">Łączna objętość: ${num(volume(w))} kg (ciężar × powtórzenia).</p></div>`}
function calendar(){const y=month.getFullYear(),m=month.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),hist=completed(),sessions=hist.filter(w=>w.date===selectedDate);app.innerHTML=`<div class="eyebrow">Twoja regularność</div><h1>Kalendarz treningów</h1><div class="layout"><section class="panel"><div class="row"><h2 class="date-heading">${month.toLocaleDateString('pl-PL',{month:'long',year:'numeric'})}</h2><div class="month-control"><button data-month="-1" aria-label="Poprzedni miesiąc">‹</button><button data-month="1" aria-label="Następny miesiąc">›</button></div></div><div class="calendar">${['PN','WT','ŚR','CZ','PT','SO','ND'].map(s=>`<span class="weekday">${s}</span>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const d=localDate(new Date(y,m,i+1)),n=hist.filter(w=>w.date===d).length;return `<button data-date="${d}" class="day ${n?'has':''} ${d===selectedDate?'chosen':''} ${d===localDate()?'current':''}" aria-label="${fmt(d,{day:'numeric',month:'long'})}${n?', treningów: '+n:''}" aria-pressed="${d===selectedDate}">${i+1}</button>`}).join('')}</div><p class="small muted spacer">• Dzień z zapisanym treningiem</p></section><section><h2>${fmt(selectedDate,{weekday:'long',day:'numeric',month:'long'})}</h2>${sessions.length?sessions.map(detail).join(''):'<div class="empty">Brak zapisanego treningu w tym dniu.</div>'}</section></div>`}
function progress(){const data=completed().reverse().flatMap(w=>{const e=w.exercises.find(e=>e.id===progressId),sets=e?.sets.filter(s=>s.done)||[];return sets.length?[{date:w.date,sets,max:Math.max(...sets.map(s=>Number(s.kg))),volume:sets.reduce((n,s)=>n+Number(s.kg)*Number(s.reps),0)}]:[]}),max=Math.max(1,...data.map(d=>d.max)),last=data.at(-1);app.innerHTML=`<div class="eyebrow">Seria po serii</div><h1>Twój progres</h1><div class="layout"><section><label for="progress-ex" class="small muted">Ćwiczenie</label><select id="progress-ex">${Object.entries(names).map(([id,n])=>`<option value="${id}" ${id===progressId?'selected':''}>${n}</option>`).join('')}</select>${data.length?`<div class="stats"><div class="stat"><strong>${num(max===1&&data.every(d=>d.max===0)?0:max)}<span> kg</span></strong><span>Największy ciężar</span></div><div class="stat"><strong>${num(last.max)}<span> kg</span></strong><span>Ostatnio</span></div><div class="stat"><strong>${data.length}</strong><span>Treningów</span></div></div><div class="panel"><h2>Ciężar na treningu</h2><p class="small muted">Najcięższa wykonana seria · ostatnie 8 treningów</p><div class="chart" role="img" aria-label="Ciężar maksymalny na kolejnych treningach">${data.slice(-8).map(d=>`<div class="barrow"><span class="muted">${fmt(d.date)}</span><div><div class="bar" style="width:${d.max/max*100}%"></div></div><strong>${num(d.max)} kg</strong></div>`).join('')}</div></div>`:'<div class="empty">Jeszcze nie ma wyników tego ćwiczenia.<br>Zapisz pierwszy trening, a zobaczysz tutaj ciężary i powtórzenia.</div>'}</section><section><h2>Historia ćwiczenia</h2>${data.length?data.slice().reverse().map(d=>`<section class="exercise-preview" style="display:block"><div class="row"><strong>${fmt(d.date,{day:'numeric',month:'long',year:'numeric'})}</strong><span>${num(d.volume)} kg</span></div><p class="small muted">${d.sets.map(s=>`${num(s.kg)} kg × ${s.reps}`).join(' · ')}</p></section>`).join(''):'<p class="muted">Twoje wyniki pojawią się po zakończeniu treningu.</p>'}</section></div>`}
app.addEventListener('input',e=>{const t=e.target;if(!t.dataset.current||!active||wizardBusy)return;const s=currentSet();if(!s)return;s[t.dataset.current]=t.value;s.done=false;if(t.value===''||t.validity.valid)scheduleSave()});
app.addEventListener('change',e=>{const t=e.target;if(t.id==='progress-ex'){progressId=t.value;progress()}if(t.id==='workout-date'){if(t.value&&t.value<=localDate()){active.date=t.value;scheduleSave()}else{t.value=active.date;toast('Wybierz dzisiejszą lub wcześniejszą datę.')}}});
app.addEventListener('submit',e=>{if(e.target.id==='series-form'){e.preventDefault();nextSeries()}});
app.addEventListener('click',e=>{const b=e.target.closest('[data-wizard]');if(!b||wizardBusy)return;const a=b.dataset.wizard;if(a==='last'){nextSeries(true);return}const [i,j]=cursor();if(a==='add'){if(active.exercises[i].sets.length>=30){toast('Maksymalnie 30 serii.');return}active.exercises[i].sets.push({kg:'',reps:'',done:false});training();scheduleSave()}if(a==='back'){if(i===0&&j===0)return;active.cursor=j>0?[i,j-1]:[i-1,active.exercises[i-1].sets.length-1];training();scheduleSave()}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||wizardBusy)return;if(b.dataset.view){view=b.dataset.view;render();window.scrollTo(0,0)}if(b.dataset.plan){chosen=+b.dataset.plan;home()}if(b.dataset.action==='retry')load();if(b.dataset.action==='start'){start();window.scrollTo(0,0)}if(b.dataset.action==='save'){clearTimeout(saveTimer);persist()}if(b.dataset.add!==undefined){active.exercises[+b.dataset.add].sets.push({kg:'',reps:'',done:false});training();scheduleSave()}if(b.dataset.remove!==undefined){const sets=active.exercises[+b.dataset.remove].sets;if(sets.at(-1).done&&!confirm('Usunąć ostatnią wykonaną serię?'))return;sets.pop();training();scheduleSave()}if(b.dataset.month){month=new Date(month.getFullYear(),month.getMonth()+ +b.dataset.month,1);calendar()}if(b.dataset.date){selectedDate=b.dataset.date;calendar()}if(b.dataset.history){const w=workouts.find(w=>w.id===b.dataset.history);selectedDate=w.date;month=new Date(parseDate(w.date).getFullYear(),parseDate(w.date).getMonth(),1);view='calendar';render();window.scrollTo(0,0)}if(b.dataset.action==='finish'){if(!doneSets(active).length){toast('Zaznacz co najmniej jedną wykonaną serię.');return}clearTimeout(saveTimer);const original=JSON.parse(JSON.stringify(active));active.exercises=active.exercises.map(e=>({...e,sets:e.sets.filter(s=>s.done)})).filter(e=>e.sets.length);active.status='complete';b.disabled=true;try{const saved=await persist();active=null;selectedDate=saved.date;month=new Date(parseDate(saved.date).getFullYear(),parseDate(saved.date).getMonth(),1);view='calendar';render();window.scrollTo(0,0);toast('Trening zapisany. Dobra robota!')}catch{active=original;b.disabled=false}}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_workout_history',description:'Odczytaj zapisane zakończone treningi i ich serie.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Oczekiwano pustego obiektu');return {workouts:completed()}}})).catch(()=>{})}catch{}}
load().finally(()=>{document.querySelector('#splash')?.remove()});

function backupControls(){return LOCAL_MODE?`<details class="backup"><summary>Kopia danych i aplikacja</summary><p class="small muted">Historia jest zapisana tylko w tej przeglądarce. Pobieraj kopię przed zmianą telefonu lub czyszczeniem danych.</p><button data-backup="export">Pobierz kopię</button><button data-backup="import">Wczytaj kopię</button><input type="file" accept="application/json,.json" id="backup-file" hidden><p class="small muted">Dodaj tę stronę do ekranu głównego w menu przeglądarki. Po pierwszym otwarciu działa także offline.</p></details>`:''}
function validBackup(data){return Array.isArray(data)&&data.length<=10000&&data.every(w=>w&&typeof w.id==='string'&&w.id.length<100&&typeof w.started==='string'&&!isNaN(Date.parse(w.started))&&/^\d{4}-\d{2}-\d{2}$/.test(w.date)&&!isNaN(Date.parse(w.date))&&[0,1,2].includes(w.plan)&&['draft','complete'].includes(w.status)&&Array.isArray(w.exercises)&&w.exercises.length<=20&&w.exercises.every(e=>Object.hasOwn(names,e.id)&&Array.isArray(e.sets)&&e.sets.length<=30&&e.sets.every(s=>typeof s.done==='boolean'&&(s.kg===''||typeof s.kg==='string'||typeof s.kg==='number')&&(s.reps===''||typeof s.reps==='string'||typeof s.reps==='number')&&(s.kg===''||Number.isFinite(+s.kg)&&+s.kg>=0&&+s.kg<=2000)&&(s.reps===''||Number.isInteger(+s.reps)&&+s.reps>=1&&+s.reps<=1000)&&(!s.done||s.kg!==''&&s.reps!==''))))}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-backup]');if(!b||!LOCAL_MODE)return;if(b.dataset.backup==='import')document.querySelector('#backup-file').click();if(b.dataset.backup==='export'){try{await saveQueue;const data=await readWorkouts();const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,workouts:data},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='trening-bartka-'+localDate()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch{toast('Nie udało się utworzyć kopii. Spróbuj ponownie.')}}});
document.addEventListener('change',async e=>{if(e.target.id!=='backup-file'||!LOCAL_MODE)return;const file=e.target.files[0];if(!file)return;try{if(file.size>20000000)throw Error();const data=JSON.parse(await file.text());if(data.version!==1||!validBackup(data.workouts))throw Error();if(!confirm('Połączyć kopię z historią? Wpisy o tych samych identyfikatorach zostaną zastąpione.'))return;await saveQueue;const byId=new Map((await readWorkouts()).map(w=>[w.id,w]));data.workouts.forEach(w=>byId.set(w.id,w));localStorage.setItem(STORAGE_KEY,JSON.stringify([...byId.values()]));await load();toast('Kopia została wczytana.')}catch{toast('Nie udało się wczytać kopii. Sprawdź plik i dostępne miejsce.')}});

if('serviceWorker' in navigator&&location.protocol==='https:'){window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js').catch(()=>{})})}
